version: "3.8"

services:
    main:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - "4000:4000"
        depends_on:
            - django
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
